### ISSUE TITLE
read model file based on created meta-model

### ISSUE THREAD

**Issue by Mohamedgalil** [catedrasaes-umu/emf4cpp#10]
I created a meta-model, generated the corresponding cpp code, created an xml file corresponding to my meta-model with the extension ".test_meta_model" and want to read this file. What are the steps?

**Comment by srhenning** [comment]
Hello Mohamed,

reading a serialized model instance can be done in two ways. With a simple parser which can read a single model instance but can not resolve cross-document references. An example usage of this method can be found in the emf4cpp tests: emp4cpp.tests/company/test/test.cpp.
The preferred way, however, is to use the resource framework (located in emf4cpp/ecorecpp/resource). The following steps are necessary to load a model:

- register your meta-model package(s) in the MetaModelRepository
- register a new XMLResourceFactory for files in the protocol to factory map of the global ResourceSet
- create a file url (QUrl)
- create a new resource for the file
- load the resource.

After these steps the root node of your model instance can be found in the contents list of the resource. 

Examples of using a resource for parsing a model instance can be found in emf4cpp.tests/resource/test/.

Best regards,
Soeren

**Comment by Mohamedgalil** [comment]
Hello Soeren,

thanks for your reply. Can you provide an example? In both examples provided under emf4cpp.tests/resource/test/ namely `test-uriconverter.cpp` and `test-options.cpp`, the resource is still loaded using the parser, as shown in the following snippets:
```
// in test-uriconverter.cpp lines 54-56
::ecorecpp::MetaModelRepository::_instance()->load(::ResourceTests::ResourceTestsPackage::_instance());
auto resource3 = rSet2.createResource(file1);
resource3->load();
```
```
// in test-options.cpp line 17
::ecorecpp::MetaModelRepository::_instance()->load(::ResourceTests::ResourceTestsPackage::_instance());
```
This doesn't support loading a model which adheres to a meta-model referring to another meta-model.

Looking forwards for your reply.

Thanks
Mohamed

**Comment by mdoerfel** [comment]
Hi Mohamed,

this is actually quite easy: Once you loaded all your metamodels into the MetaModelRepository, you can load any Resource and the Resource will select the matching metamodel according to the header given in the XMI. If an object instance within an XMI refers to a different metamodel (I assume this is what you refer to in your last sentence), the parser will use the referred metamodel.

Emf4cpp is even able to resolve external resources, where an object refers to a different file and a fragment path in this file. In that case a new Resource will be added to the ResourceSet automatically and the object instances from different Resources are pointing to each other. This is called a "cross-document reference".

This is a snippet from our code:

```
/* Some initialization */
auto mmr = ecorecpp::MetaModelRepository::_instance();
mmr->load(::projects::ProjectsPackage::_instance());
mmr->load(::root::RootPackage::_instance());

/* Now we are using the Resource for loading the XMI. */
using ::ecorecpp::resource::Resource;
using ::ecorecpp::resource::ResourceSet;

QUrl file = QUrl::fromLocalFile( YOUR_FILENAME_HERE );
ResourceSet::getInstance().getResourceFactoryRegistry()
		->getProtocolToFactoryMap()[ file.scheme().toStdString() ].reset(
				new ::ecorecpp::resource::XMLResourceFactory() );

ecore::Ptr<Resource> input = ResourceSet::getInstance().createResource(file);
try { 
    input->load();
} catch (std::logic_error error) { /* handle your errors */ }

/* This is the toplevel element of the loaded file
ecore::EObject_ptr eobj = input->getContents()->get(0);
```

Best regards,
Matthias

**Comment by Mohamedgalil** [comment]
I tried the code snippet, however, I still get the error `missing package: ONE_OF_MY_PACKAGES`. My code is as follows:
```
// some includes
#include <standardized_problem/Standardized_problemPackage.hpp>
#include <basicAttributes/BasicAttributesPackage.hpp>
#include <typeinfo>
//main...
auto mmr = ::ecorecpp::MetaModelRepository::_instance();
mmr->load(::standardized_problem::Standardized_problemPackage::_instance());
mmr->load(::basicAttributes::BasicAttributesPackage::_instance());
    
using ::ecorecpp::resource::Resource;
using ::ecorecpp::resource::ResourceSet;
// package standardized_problem depends on package baseAttributes
QUrl file = QUrl::fromLocalFile("./sp.standardized_problem");
ResourceSet::getInstance().getResourceFactoryRegistry()
			->getProtocolToFactoryMap()[file.scheme().toStdString()].reset(
					new ::ecorecpp::resource::XMLResourceFactory());

ecore::Ptr<Resource> resource = ResourceSet::getInstance().createResource(file);
resource->load();
/*
throws the following error:
 terminate called after throwing an instance of 'std::logic_error'
what():  missing package: BasicAttributes
Aborted (core dumped)
*/
```

**Comment by srhenning** [comment]
[modelchaining.zip](https://github.com/catedrasaes-umu/emf4cpp/files/2845553/modelchaining.zip)
Hello Mohamed,

I have created a minimal example project consisting of two ecore models: 'basicTypes.ecore' and 'advancedProject.ecore'. The advanced project model uses a class definition from basicTypes as
child containment reference of class 'AdvancedClass'. The attached zip file contains the ecore files,
the generated code, and two test programs for writing and reading an instance of this model.

If this example does not help you to solve your problems it would be very helpful for us if you could send us a minimal working example (ecore and xmi) which shows the problem so that we can analyze it in more detail.

Best regards,
Sören

**Comment by Mohamedgalil** [comment]
Dear Sören,

I tried your example and it works. But when I try it on my project it gives me pointer error. Please find attached my project: [libv3_1.tar.gz](https://github.com/catedrasaes-umu/emf4cpp/files/2855040/libv3_1.tar.gz)
The structure is as follows
- ecore: contains all the metamodel ecores. "standardized_problem" is my main package which refers to many other packages/ecores
- src-gen: contains all generated files
-  testProject/test-create.cpp:  tries to create a standardized_problem xml but fails and throws the following error:
```./test-create 
test-create: /usr/include/boost/smart_ptr/intrusive_ptr.hpp:174: T* boost::intrusive_ptr<T>::operator->() const [with T = ecore::EObject]: Assertion `px != 0' failed.
Aborted (core dumped)
```
- testProject/test.cpp reads the "sp.standardized_problem", but throws the following error:
```
./test-read 
terminate called after throwing an instance of 'std::logic_error'
  what():  missing package: BasicAttributes
Aborted (core dumped)
```
- generate_code.sh: contains all commands to generate code from ecore. Just change the variables inside to point to the EMF4CPP and the ecore directories. Hint: The code is already generated in src-gen. If regenerating code is necessary, better to move it inside src-gen to generate the files their. 



I would appreciate any hints of the possible causes of the error or any guidance. Thank you a lot in advance!

Best regards
Mohamed

**Comment by srhenning** [comment]
Hello Mohamed,

I found two issues in your project:

- a c++-keyword is used as literal in the enumeration 'VisibilityType' of 'stateMachine.ecore'. If you replace 'public' by e.g. 'external' the generated code compiles.
- The name of the basicAttributes package starts with a lower case letter. However the references in 'sp.standardized_problem' start with an upper case letter. This is the reason, why the package can not be found. Just replace all upper case package references in 'sp.standardized_problem' by lower case ones and it will work (e.g.:  xsi:type="BasicAttributes:PrimitiveType" -> xsi:type="basicAttributes:PrimitiveType".

Best regards,
Sören

**Comment by Mohamedgalil** [comment]
Hi Sören,

thank you very much for your feedback and support. The tool now works when I corrected the two mentioned issues! I will close this issue.

Best regards,
Mohamed
