### ISSUE TITLE
Emf4Cpp support XMI

### ISSUE THREAD

**Issue by Mohamedgalil** [catedrasaes-umu/emf4cpp#11]
Does EMF4CPP support XMI? Since I only found XMLResourceFactory but not a XMIResourceFactory.

**Comment by srhenning** [comment]
Hello Mohamed,

XMI is supported by the XMLResource so there is no need for a special XMIResource.

Regards,
Soeren

**Comment by Mohamedgalil** [comment]
Then I will close this issue and will refer back to my other question:
https://github.com/catedrasaes-umu/emf4cpp/issues/10#issuecomment-460985124
