### ISSUE TITLE
cannot convert ‘ecore::EClass*’ to ‘ecore::EObject*’ for argument ‘1’ to ‘void ecore::intrusive_ptr_release(ecore::EObject*)’

### ISSUE THREAD

**Issue by RamakrishnanOSS** [catedrasaes-umu/emf4cpp#12]
I have tried creating a simple model then generated using the generator available with the "Downloads" section of your project.

But I end up always with this error:

> cannot convert ‘ecore::EClass*’ to ‘ecore::EObject*’ for argument ‘1’ to ‘void ecore::intrusive_ptr_release(ecore::EObject*)’

PS: I have also used the compiled libraries from the "master" branch of the git repo as well.

**System details:** 
Linux ubuntu 4.18.0-21-generic
cmake: 3.10.2
boost: 1.65.1.0ubuntu1
g++: 7.4.0-1ubuntu1~18.04
Qt: 5.9.5+dfsg-0ubuntu2.1
JRE: openjdk version "1.8.0_212"

**ECORE:** 

```
<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="root" nsURI="www.bosch.com/root" nsPrefix="root">
  <eClassifiers xsi:type="ecore:EClass" name="Class_1">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="c" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="d" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Class_2">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="a" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="b" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
</ecore:EPackage>
```

**Comment by srhenning** [comment]
Hello Ramakrishnan,

before you can start using the code generator you have to build the code generator itself. Follow the steps described in section 'Installation from source distribution' to this end. After generation of the code generator (org.csu.emf4cpp.generator_2.0.0.jar in folder org.csu.emf4cpp.generator) you can run the ./generator-release.sh script in the builds folder (call ./cleanup.sh first if you have any residuals from previous attempts). The ready-to-use library can be found in folder 'emf4cpp-generator-2.0.0' after this step. Now you should be able to generate code from your model by calling libraryfolder/bin/emf4cpp.generator.sh test.ecore and build the generated code into a library.

Best regards,
Soeren

**Comment by RamakrishnanOSS** [comment]
Hello Soeren,

Thanks for your response. I did lot of tries after posting the query and I think it worked with setting the default JDK,JRE to  openJDK11.

Regards,
Ramakrishnan
