### ISSUE TITLE
Issues with merged pull request #5

### ISSUE THREAD

**Issue by mdoerfel** [catedrasaes-umu/emf4cpp#7]
Dear Team,

after some time with no response from @qvitech we suggest to revert pull request #5 completely for the following reasons:

1. The emf4cpp generator cannot be built: org.csu.emf4cpp.generator/src/template/PackageImpl.xpt, line 51 calls the undefined function getFQN2(). Hence the jar file of the generator cannot be built.
2. Code was added to the ecore implementation outside of a PROTECTED REGION. The ecore implementation itself will be generated during the bootstrap process of the library. Any code outside of PROTECTED_REGIONs will be removed automatically.
3. The changes in org.csu.emf4cpp.generator/src/template/EClassImplCPP.xpt may seem like an innocent optimization, but it removes the possibility to set/get attributes of base classes via the generic eSet()/eGet() methods of derived instances. Actually we do not see how serialization or deserialization of class hierarchies continues to work at all after this change.

Regards,
Matthias.

**Comment by mdoerfel** [comment]
I have created pull request #8 to revert the changes. Please accept it.

**Comment by dsevilla** [comment]
Accepted. Closing.
